In [1]:
import numpy as np

# CREATING TWO RANDOM 2x2 MATRICES

In [ ]:
np.random.seed(3)

In [42]:
A = np.random.randint(low=0, high=11, size=(2,2))
B = np.random.randint(low=2, high=13, size=(2,2))

print(f"MATRIX A is:\n{A}")
print(f"Shape of MATRIX A is {A.shape}")
print()
print(f"MATRIX B is:\n{B}")
print(f"Shape of MATRIX B is {B.shape}")

MATRIX A is:
[[2 4]
 [5 8]]
Shape of MATRIX A is (2, 2)

MATRIX B is:
[[10  9]
 [ 7  3]]
Shape of MATRIX B is (2, 2)


## Element Wise Multiplication

In [43]:
ew_mul = A*B
print(ew_mul)
print(f"Shape of the matrix is: {ew_mul.shape}")

[[20 36]
 [35 24]]
Shape of the matrix is: (2, 2)


## Matrix Multiplication

In [44]:
mat_mul = A@B
print(mat_mul)
print(f"Shape of the matrix is: {mat_mul.shape}")

[[ 48  30]
 [106  69]]
Shape of the matrix is: (2, 2)


# COMPUTING INVERSE AND DETERMINANT

## Determinant Calculations

In [16]:
det_A = np.linalg.det(A)
print(det_A)

-42.00000000000002


In [18]:
det_B = np.linalg.det(B)
print(det_B)

50.000000000000014


## Inverse Calculations

In [45]:
inv_A = np.linalg.inv(A)
print(inv_A)
print(f"Shape of the matrix is: {inv_A.shape}")

[[-2.    1.  ]
 [ 1.25 -0.5 ]]
Shape of the matrix is: (2, 2)


In [46]:
inv_B = np.linalg.inv(B)
print(inv_B)
print(f"Shape of the matrix is: {inv_B.shape}")

[[-0.09090909  0.27272727]
 [ 0.21212121 -0.3030303 ]]
Shape of the matrix is: (2, 2)


# NORMALIZING A 1D ARRAY

In [47]:
arr_one_D = np.array([10,14,37,50])
print(f"Shape of the matrix is: {arr_one_D.shape}")

Shape of the matrix is: (4,)


In [48]:
normalized_arr = (arr_one_D - arr_one_D.min()) / (arr_one_D.max() - arr_one_D.min())
print(normalized_arr)
print(f"Shape of the matrix is: {normalized_arr.shape}")

[0.    0.1   0.675 1.   ]
Shape of the matrix is: (4,)


# DEMONSTRATING BROADCASTING

In [51]:
column_mean = np.mean(A, axis=0)
print(f"Shape of the column mean is: {column_mean.shape}")

new_A = A - column_mean

print()
print(new_A)
print(f"Shape of the matrix is: {new_A.shape}")

Shape of the column mean is: (2,)

[[-1.5 -2. ]
 [ 1.5  2. ]]
Shape of the matrix is: (2, 2)
